package com.acm.msgtomail;

import org.apache.dubbo.config.spring.context.annotation.EnableDubbo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@EnableDubbo
@SpringBootApplication(exclude= {DataSourceAutoConfiguration.class})

public class TaskManageSysMsgToMailApplication {

    public static void main(String[] args) {
        SpringApplication.run(TaskManageSysMsgToMailApplication.class, args);
    }

}
