spring:
  application:
    name: taskManageSys-giveTask
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.acm.front
  consumer:
    check: false
    timeout: 50000
    retries: 0
  protocol:
    name: dubbo
    port: 20884
server:
  port: 8000
  servlet:
    context-path: /tms
    encoding:
      charset: utf-8
      enabled: true
      force: true
