spring:
  application:
    name: taskManageSys-viewTask
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.acm.givetask
  consumer:
    check: false
    timeout: 50000
    retries: 0
  protocol:
    port: 20881
    name: dubbo


server:
  port: 8001
  servlet:
    context-path: /tms
    encoding:
      charset: utf-8
      enabled: true
      force: true


